# -*- python -*-
Import("env")

import eups
import lsst.tests

tests = lsst.tests.Control(env, ignoreList=[])

dataDir = eups.productDir("afwdata")
if not dataDir:
    print "Warning: afwdata is not set up; not running the tests that use it"

for target in tests.run("*.py"):
    env.Depends(target, "../python/lsst/coadd/utils/_utilsLib%s" % (env["LDMODULESUFFIX"]))
